#ifndef _SETTINGS_PARAMS_
#define _SETTINGS_PARAMS_
#include <kamek.hpp>
#include <PulsarSystem.hpp>
#include <Config.hpp>

namespace Pulsar {
namespace UI { class SettingsPanel; }
namespace Settings {

class Params {
public:
    static const int pulsarPageCount = 6;
    static const int userPageCount = 0;
    static const int pageCount = pulsarPageCount + userPageCount;

    static const int maxRadioCount = 8;
    static const int maxScrollerCount = 8;

    static u8 radioCount[pageCount];
    static u8 scrollerCount[pageCount];
    static u8 buttonsPerPagePerRow[pageCount][maxRadioCount];
    static u8 optionsPerPagePerScroller[pageCount][maxScrollerCount];

};

enum Type {
    SETTINGSTYPE_MENU,
    SETTINGSTYPE_RACE,
    SETTINGSTYPE_HOST,
    SETTINGSTYPE_OTT,
    SETTINGSTYPE_KO,
    SETTINGSTYPE_RACE2,
};

enum UserType {

};

}//namespace Settings

enum MenuSettings {
    SETTINGMENU_RADIO_FASTMENUS = 0,
    SETTINGMENU_RADIO_LAYOUT = 1,
    SETTINGMENU_RADIO_MUSIC = 2,
    SETTINGMENU_RADIO_FPS = 3,
    SETTINGMENU_RADIO_INPUTVIEWER = 4,
    SETTINGMENU_SCROLL_BOOT = 0 + 8
};

enum RaceSettings {
    SETTINGRACE_RADIO_MII = 0,
    SETTINGRACE_RADIO_SPEEDUP = 1,
    SETTINGRACE_RADIO_BATTLE = 2,
    SETTINGRACE_RADIO_BLUES = 3,
    SETTINGRACE_RADIO_SOM = 4,

    SETTINGRACE_SCROLL_SOM = 0 + 8
};

enum HostSettings {
    SETTINGHOST_RADIO_HOSTWINS = 0,
    SETTINGHOST_RADIO_CC = 1,
    SETTINGHOST_ALLOW_MIIHEADS = 2,
    SETTINGHOST_RADIO_POINT_DISTRO = 3,
    SETTINGHOST_RADIO_NO_VEHICLES = 4,

    SETTINGHOST_SCROLL_GP_RACES = 0 + 8
};

enum OTTSettings {
    SETTINGOTT_ONLINE = 0,
    SETTINGOTT_OFFLINE = 1,
    SETTINGOTT_ALLOWCHANGECOMBO = 2,
    SETTINGOTT_ALLOWUMTS = 3,
    SETTINGOTT_MUTEPTANDPLAYERS = 4,
};

enum KOSettings {
    SETTINGKO_ENABLED = 0,
    SETTINGKO_FINAL = 1,
    SETTINGKO_KOPERRACE = 0 + 8,
    SETTINGKO_RACESPERKO = 1 + 8,
};

//MENU SETTINGS
enum MenuSettingFastMenus {
    MENUSETTING_FASTMENUS_DISABLED = 0x0,
    MENUSETTING_FASTMENUS_ENABLED = 0x1
};

enum MenuSettingLayout {
    MENUSETTING_LAYOUT_DEFAULT = 0x0,
    MENUSETTING_LAYOUT_ALPHABETICAL = 0x1
};

enum MenuSettingMusic {
    MENUSETTING_MUSIC_DEFAULT = 0x0,
    MENUSETTING_MUSIC_DISABLE_ALL = 0x1,
    MENUSETTING_MUSIC_DISABLE_RACE = 0x2
};

enum MenuSettingFPS {
    MENUSETTING_FPS_60 = 0x0,
    MENUSETTING_FPS_30 = 0x1
};

enum MenuSettingBoot {
    MENUSETTING_BOOT_DISABLED,
    MENUSETTING_BOOT_L1,
    MENUSETTING_BOOT_L2,
    MENUSETTING_BOOT_L3,
    MENUSETTING_BOOT_L4
};

//RACE SETTINGS
enum RaceSettingMII {
    RACESETTING_MII_DISABLED = 0x0,
    RACESETTING_MII_ENABLED = 0x1
};

enum RaceSettingSPEEDUP {
    RACESETTING_SPEEDUP_DISABLED = 0x0,
    RACESETTING_SPEEDUP_ENABLED = 0x1
};

enum RaceSettingBATTLE {
    RACESETTING_BATTLE_GLITCH_DISABLED = 0x0,
    RACESETTING_BATTLE_GLITCH_ENABLED = 0x1
};

enum RaceSettingBLUES {
    RACESETTING_DRAGGABLE_BLUES_DISABLED = 0x0,
    RACESETTING_DRAGGABLE_BLUES_ENABLED = 0x1
};

enum RaceSettingSOM {
    RACESETTING_SOM_LEFT = 0x0,
    RACESETTING_SOM_RIGHT = 0x1,
    RACESETTING_SOM_DISABLED = 0x2
};

enum RaceSettingSOMDigits {
    HOSTSETTING_SOM_DIGITS_0,
    HOSTSETTING_SOM_DIGITS_1,
    HOSTSETTING_SOM_DIGITS_2,
    HOSTSETTING_SOM_DIGITS_3,
};

enum MenuSettingInputViewer {
    MENUSETTING_INPUTVIEWER_DISABLED = 0x0,
    MENUSETTING_INPUTVIEWER_ENABLED = 0x1
};

//HOST SETTINGS
enum HostSettingHAW {
    HOSTSETTING_HOSTWINS_DISABLED,
    HOSTSETTING_HOSTWINS_ENABLED
};

enum HostSettingHostCC {
    HOSTSETTING_CC_NORMAL,
    HOSTSETTING_CC_150,
    HOSTSETTING_CC_100,
    HOSTSETTING_CC_MIRROR
};

enum HostSettingMiiHeads {
    HOSTSETTING_ALLOW_MIIHEADS_ENABLED,
    HOSTSETTING_ALLOW_MIIHEADS_DISABLED
};

enum HostSettingGPRACES {
    HOSTSETTING_GP_RACES_4,
    HOSTSETTING_GP_RACES_8,
    HOSTSETTING_GP_RACES_12,
    HOSTSETTING_GP_RACES_24,
    HOSTSETTING_GP_RACES_32,
    HOSTSETTING_GP_RACES_64,
    HOSTSETTING_GP_RACES_2,
    //space for a 7th setting is available
};

enum HostSettingPointDistro {
    HOSTSETTING_POINT_DISTRO_TIME,
    HOSTSETTING_POINT_DISTRO_RACE
};

enum HostSettingNoVehicles {
    HOSTSETTING_NO_VEHICLES_DISABLED = 0x0,
    HOSTSETTING_NO_VEHICLES_ENABLED = 0x1
};

//OTTSETTINGS
enum OTTSettingOnline {
    OTTSETTING_ONLINE_DISABLED,
    OTTSETTING_ONLINE_NORMAL,
    OTTSETTING_ONLINE_FEATHER,
};

enum OTTSettingOffline {
    OTTSETTING_OFFLINE_DISABLED,
    OTTSETTING_OFFLINE_NORMAL,
    OTTSETTING_OFFLINE_FEATHER,
};

enum OTTSettingCombo {
    OTTSETTING_COMBO_DISABLED,
    OTTSETTING_COMBO_ENABLED
};

enum OTTSettingUMTs {
    OTTSETTING_UMTS_DISABLED,
    OTTSETTING_UMTS_ENABLED
};

//KOSETTINGS
enum KOSettingEnabled {
    KOSETTING_DISABLED,
    KOSETTING_ENABLED,
};
enum KOSettingFINAL {
    KOSETTING_FINAL_DISABLED,
    KOSETTING_FINAL_ALWAYS,
};
enum KOSettingKOPerRace {
    KOSETTING_KOPERRACE_1,
    KOSETTING_KOPERRACE_2,
    KOSETTING_KOPERRACE_3,
    KOSETTING_KOPERRACE_4
};

enum KOSettingRacesPerKO {
    KOSETTING_RACESPERKO_1,
    KOSETTING_RACESPERKO_2,
    KOSETTING_RACESPERKO_3,
    KOSETTING_RACESPERKO_4
};

enum Race2Settings {
    SETTINGRACE2_RADIO_TRIPLE_BANANAS = 0,
    SETTINGRACE2_RADIO_TURN_IN_AIR = 1,
    SETTINGRACE2_RADIO_TRICK_CHAINING = 2,
    SETTINGRACE2_RADIO_BRAKE_DRIFTING = 3,
};

//RACE2 SETTINGS
enum Race2SettingTripleBananas {
    RACE2SETTING_TRIPLE_BANANAS_TRAIL = 0x0,
    RACE2SETTING_TRIPLE_BANANAS_ROTATE = 0x1
};

enum Race2SettingTurnInAir {
    RACE2SETTING_TURN_IN_AIR_DISABLED = 0x0,
    RACE2SETTING_TURN_IN_AIR_ENABLED = 0x1
};

enum Race2SettingTrickChaining {
    RACE2SETTING_TRICK_CHAINING_ENABLED = 0x0,
    RACE2SETTING_TRICK_CHAINING_DISABLED = 0x1
};

enum Race2SettingBrakeDrifting {
    RACE2SETTING_BRAKE_DRIFTING_DISABLED = 0x0,
    RACE2SETTING_BRAKE_DRIFTING_ENABLED = 0x1
};

}//namespace Pulsar



#endif